version: "3.7"

services:
  server:
    build:
      dockerfile: server/Dockerfile
      context: ./
    container_name: "server"
  client:
    build:
      dockerfile: client/Dockerfile
      context: ./
    container_name: "client"
    